version: "3"
services:
  php:
    build:
      context: ./php/
      dockerfile: Dockerfile
    ports:    
      - 8000:80
    volumes:
      - ./php/src:/var/www/html/
    # put your env file in here but it has to be in app directory
  
  db:
    build:
      context: ./mysql/
    ports:
      - 3306:3306
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    # DB CREDENTIALS IN HIDDEN ENV FILE
    env_file: 
      - ./env/mysql.env
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
volumes:
  mysql-data:

